### ISSUE TITLE
[Feature Request]: Publish Release 0.6

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1533]
### Must have

- [x] All modules are consistently aligned to the latest cross-referenced approach
    - [x] PR #1401 is merged
    - [x] Issue #1495 is closed
    - [x] PR #1494 is merged
    - [x] Issue #1531 is closed

- [x] All module pipelines are green except the ones documented in the [Know Issues Wiki page](https://github.com/Azure/ResourceModules/wiki/Known%20issues). If additional pipelines are agreed to stay red, they need to be added to that page with corresponding reason.
    - [x] PR #1529 is merged
    - [x] PR #1530 is merged
    - [x] PR #1534 is merged
    - [x] Issue #1532 is closed

### Nice to have

- [x] PR #1463  is merged 
- [x] PR #1560 is merged
- [ ] PR #1453 is merged
- [x] PR #1483 is merged
- [ ] PR #1490  is merged

**Comment by MrMCake** [comment]
Note, I set some checkmarks after the corresponding issues/PRs were resolved

**Comment by MrMCake** [comment]
:shipit:

**Comment by MrMCake** [comment]
As the release was created I will close this issue.
