### ISSUE TITLE
[Bug Report]: List and fix failing module pipelines before release 0.7

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#1847]
### Describe the bug

All module pipelines are green except the ones documented in the [Know Issues Wiki page](https://github.com/Azure/ResourceModules/wiki/Known%20issues). If additional pipelines are agreed to stay red, they need to be added to that page with corresponding reason.

This issue is about listing the modules which need to be fixed, for which a dedicated issue will be opened.

- [x] #1848
- [x] #1849
- [x] Fix failing Container instances #1852 
- [x] Fix failing Container registries #1863 
- [x] Fix failing Key Vaults #1857
- [x] Fix failing Logic Apps #1859
- [x] #1860
- [x] #1858
- [x] #1856
- [x] #1853
- [x] #1851
- [x] #1850
- [x] #2020
- [x] #2023
- [x] #2029 
- [x] #2031
- [x] #2034
- POSTPONED (depending on Bicep versioning) #2032 

### To reproduce

Go through the list of module pipeline runs [here](https://github.com/Azure/ResourceModules#available-resource-modules) and rerun the failing ones
