### ISSUE TITLE
[PSRule] Discuss PSRule validation results and update modules/module tests accordingly

### ISSUE THREAD

**Issue by eriqua** [Azure/ResourceModules#2151]
Analyze the output of PSRule validation. List all modules to be updated and open separated issues for each.

For each failed rule we should:
- either fix the module/module test to have it compliant
- or suppress the rule if not making sense in our scenario,documenting the reason

### Example
List of failed rules after running PSRule validation on RG, KV and VNET modules:
![image](https://user-images.githubusercontent.com/56914614/193159433-cf61fc83-4e04-4d74-aff8-0218e2c47046.png)

- Tags should be added to common tests, the ones aiming to validate all possible parameters for a module
- Purge keyvault should be suppressed. It doesn't make sense for our testing scenario because we want to clean up the environment after each test

Following the list of rules to be fixed:

```[tasklist]
### Tasks
- [ ] Azure/ResourceModules#2666
- [ ] Azure/ResourceModules#2667
- [ ] Azure/ResourceModules#2668
- [ ] https://github.com/Azure/ResourceModules/issues/3894
- [ ] https://github.com/Azure/ResourceModules/issues/3896
- [x] https://github.com/Azure/ResourceModules/issues/3418
- [ ] https://github.com/Azure/ResourceModules/issues/3917
- [ ] https://github.com/Azure/bicep-registry-modules/issues/2377
- [x] https://github.com/Azure/bicep-registry-modules/issues/2399
- [ ] [PSRule] Fix Rule Azure.VM.DiskSizeAlignment
- [ ] [PSRule] Fix Rule Azure.VM.Standalone
- [ ] [PSRule] Fix Rule Azure.VM.UseHybridUseBenefit
- [ ] [PSRule] Fix Rule Azure.VNET.UseNSGs
- [ ] [PSRule] Fix Rule Azure.WebPubSub.ManagedIdentity
- [ ] [PSRule] Fix Rule Azure.AppService.PlanInstanceCount
- [ ] [PSRule] Fix Rule Azure.Defender.AppServices
- [ ] [PSRule] Fix Rule Azure.Defender.Containers
- [ ] [PSRule] Fix Rule Azure.Defender.Servers
- [ ] [PSRule] Fix Rule Azure.Defender.SQL
- [ ] [PSRule] Fix Rule Azure.Defender.SQLOnVM
- [ ] [PSRule] Fix Rule Azure.Defender.Storage
- [ ] [PSRule] Fix Rule Azure.LB.Probe
- [ ] [PSRule] Fix Rule Azure.ServiceFabric.AAD
- [ ] [PSRule] Fix Rule Azure.SignalR.ManagedIdentity
- [ ] [PSRule] Fix Rule Azure.SQL.AAD
- [ ] [PSRule] Fix Rule Azure.SQL.Auditing
- [ ] [PSRule] Fix Rule Azure.SQL.DefenderCloud
- [ ] [PSRule] Fix Rule Azure.Storage.ContainerSoftDelete
- [ ] [PSRule] Fix Rule Azure.Storage.Firewall
- [ ] [PSRule] Fix Rule Azure.Storage.SoftDelete
- [ ] [PSRule] Fix Rule Azure.Deployment.AdminUsername
- [ ] https://github.com/Azure/ResourceModules/issues/3987
- [ ] https://github.com/Azure/ResourceModules/issues/3997
```

**Comment by eriqua** [comment]
Suggestion: keep in triage with the `needsfurtherdiscussion` label until refinement completion. This will include the list of modules to be fixed based on the outcome of issue #2425

**Comment by elanzel** [comment]
Following list of failing rules:
[Failed_PSRule_Output_v02.xlsx](https://github.com/Azure/ResourceModules/files/10492174/Failed_PSRule_Output_v02.xlsx)

**Comment by elanzel** [comment]
@eriqua we have completed rules' review. Can we have a call to discuss all the decisions and create issues?

**Comment by AlexanderSehr** [comment]
Covered in AVM by the PSRule reliability tests
