### ISSUE TITLE
[Feature Request]: AVM alignment tracker 

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#4020]
### Description

This issue is intended to track the efforts for alinging the CARML modules to the Azure Verified Module (AVM) [specs](https://azure.github.io/Azure-Verified-Modules/specs), ultimately enabling us to publish the CARML modules to the [Public Bicep Registry](https://github.com/Azure/bicep-registry-modules).

# Bulk edits
These can ideally be updated 'on scale', with the already defined [interfaces](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces) & conventions (e.g., folder structure), that must be updated in all modules (while taking individual characterists into account).
> **Note**: Some of these changes may require changes to the CI environment.

<details>
<summary>Checklist</summary>

- [ ] #4057
- [x] #4131
- [x] #4151
- [x] #4123
- [x] #4110
- [x] #4157
- [x] #4052
- [x] #4108
- [x] #4172
- [x] Once `Set-ModuleReadMe` script is updated, remove & regenerate all ReadMes
- [x] #4207
- [x] #4209
</details>

# Per-module edits
Side-by-side / following the alignment to the extension interface, the following list should be used to track the 'full' alignment of the modules (e.g., PSRule compliance, etc.)

<details>
<summary>Checklist</summary>

- [x] Align `aad/domain-service` to AVM specs
- [x] #4398
- [x] #4355
- [x] #4489
- [x] Align `app/jobs` to AVM specs
- [x] #4442
- [x] #4504
- [x] #4311
- [x] #4056
- [x] #4399
- [ ] Align `cache/redis-enterprise` to AVM specs
- [x] #4510
- [x] #4055
- [x] #4411
- [x] #4406
- [x] #4425
- [x] #4422
- [x] #4400
- [x] #4426
- [x] #4075
- [x] #4107
- [x] #4502
- [x] #4407
- [x] #4481
- [x] #4456
- [x] #4194
- [x] #4376
- [x] #4405
- [x] #4402
- [x] #4401
- [x] #4305
- [x] #4473
- [x] #4475
- [x] #4474
- [x] #4476
- [x] #4412
- [x] #4141
- [x] #4321
- [x] #4384
- [x] #4148
- [x] #4385
- [x] #4479
- [x] #4404
- [x] #4531
- [x] #4074 
- [x] #4344
- [x] #4268
- [x] #4332
- [x] #4333
- [x] #4249
- [x] #4343
- [x] #4413
- [x] #4345
- [x] #4377
- [x] #4063
- [x] #4054
- [x] #4053
- [x] #4180
- [x] #4458
- [x] #4378
- [x] #4149
- [x] Align `managed-services/registration-definition` to AVM specs
- [x] #4496
- [x] #4403
- [x] Align `network/application-gateway` to AVM specs
- [x] #4532
- [x] #4490
- [x] #4507
- [x] #4324
- [x] #4389
- [x] #4408
- [x] #4139
- [x] #4101
- [x] #4163
- [x] #4264
- [x] #4265
- [x] #4432
- [x] #4433
- [x] #4434
- [x] #4414
- [x] #4044
- [x] #4383
- [x] #4382
- [x] #4062
- [x] #4415
- [x] #4443
- [x] #4140
- [x] #4064
- [x] #4416
- [x] #4043
- [x] #4323
- [x] #4444
- [x] Align `network/service-endpoint-policy` to AVM specs
- [x] #4314 
- [x] Align `network/virtual-hub` to AVM specs
- [x] #4061
- [x] #4386
- [x] Align `network/virtual-wan` to AVM specs
- [x] #4387
- [x] #4390
- [x] #4060
- [x] #4059
- [x] #4337
- [x] #4460
- [x] #4494
- [x] #4528
- [x] #4445
- [x] #4198
- [x] #4430
- [x] #4266
- [x] (pattern) Align `security/azure-security-center` to AVM specs
- [x] #4179
- [x] Align `service-fabric/cluster` to AVM specs
- [x] #4511
- [x] #4514
- [x] Align `sql/managed-instance` to AVM specs
- [x] #4270
- [x] #4058
- [x] #4480
- [x] #4467
- [x] #4417
- [x] #4529
- [x] Align `web/hosting-environment` to AVM specs
- [x] #4423
- [x] #4438
- [x] #4446

</details>

## Migration Guide
This section provides a checklist of things to look out for per module to ensure they're AVM compliant, both as per [module specifications](https://azure.github.io/Azure-Verified-Modules/specs/module-specs/) & the [Contribution Guide](https://azure.github.io/Azure-Verified-Modules/contributing/bicep).

<details>
<summary>Checklist</summary>

1.  Tests ([ref](https://azure.github.io/Azure-Verified-Modules/specs/bicep/#id-bcpnfr9---category-testing---expected-test-directories))
    - [ ] Rename test folder and add nested `e2e` folder ([ref](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/#example-directory-and-file-structure-within-azurebicep-registry-modules-repository))
    - [ ] Rename `min` folder to `defaults`
    - [ ] Rename `common` folder to `max`
    - [ ] Add `waf-aligned` folder (e.g., based on `common`). This test should not fail PSRule & show the module being deployed with best-practices
    - [ ] For each folder,
    - [ ] Update the `serviceShort` parameter to align with the new naming (e.g., `waf` for `waf-aligned`). For now, we should continue using `min` for `defaults` to align with PSRule.
    - [ ] Update the `namePrefix` input parameter value from `[[namePrefix]]` to `#_namePrefix_#` (the reason being that Bicep has a compilation issue because of the prefix & suffix in another location)
    - [ ] Update the `../../main.bicep` module template reference to `../../../main.bicep`
    - [ ] If a resource group is deployed, update the RG parameter name to the new format that also uses the `namePrefix`. For example: 
      ```bicep
      @description('Optional. The name of the resource group to deploy for testing purposes.') 
      @maxLength(90)
      param resourceGroupName string = 'dep-${namePrefix}-network.privateendpoints-${serviceShort}-rg'
      ```
    - [ ] (Optionally) add a block like the following below the target scope to render a more meaningful example in the ReadMe
      ```Bicep
      metadata name = 'Using only defaults'
      metadata description = 'This instance deploys the module with the minimum set of required parameters.'
      ```
    - [ ] You should also try and test idempotency if possible. You can do this by updating the test invocation to
      ```bicep
      @batchSize(1)
      module testDeployment '../../../main.bicep' = [for iteration in [ 'init', 'idem' ]: {
        scope: resourceGroup
        name: '${uniqueString(deployment().name, location)}-test-${serviceShort}-${iteration}'
        (...)
      }]
      ```

1. For each module that supports

   <details>
   <summary>Diagnostic Settings</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#diagnostic-settings)
   - [ ] Add the `diagnosticSettingType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Remove any of the current diagnosticSetting parameters & variables
   - [ ] Add the the new `diagnosticSettings` parameter as per the specs to the template
   - [ ] Updated the deployment block as per the specs to enable it to work with the new object type
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     diagnosticSettings: [
       {
         name: 'customSetting'
         eventHubName: diagnosticDependencies.outputs.eventHubNamespaceEventHubName
         eventHubAuthorizationRuleResourceId: diagnosticDependencies.outputs.eventHubAuthorizationRuleId
         storageAccountResourceId: diagnosticDependencies.outputs.storageAccountResourceId
         workspaceResourceId: diagnosticDependencies.outputs.logAnalyticsWorkspaceResourceId
       }
     ]
     ```
   > **NOTE:** ⚠️ Make sure that if the module does not support e.g. metrics, that you update the logic accordingly

   </details>

   <details>
   <summary>Role Assignments</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#role-assignments)
   - [ ] Add the `roleAssignmentType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Update the current `roleAssignments` parameter as per the specs (- should now reference the User-defined-type)
   - [ ] Take the current list of `builtInRoleNames` from the `nested_roleAssignments.bicep` file and add them to the variables block of the main template. The new schema does not require the nested template. Also, reduce the list of specified roles to only those that make sense for this resource ([ref](https://azure.github.io/Azure-Verified-Modules/specs/bicep/#id-bcpnfr5---category-composition---role-assignments-role-definition-mapping-limits))/ For, for example, Cognitive Services, we should only provide the important ones as Owner, Contributor, etc. + all service specific roles such as 'Cognitive Services User'.
   - [ ] Replace the original module deployment block with the new resource deployment block
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     roleAssignments: [
       {
         roleDefinitionIdOrName: 'Reader'
         principalId: nestedDependencies.outputs.managedIdentityPrincipalId
         principalType: 'ServicePrincipal'
       }
     ]
     ```

   </details>

   <details>
   <summary>Resource Locks</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#resource-locks)
   - [ ] Add the `lockType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Update the current `lock` parameter as per the specs (- should now reference the User-defined-type)
   - [ ] Updated the deployment block as per the specs to enable it to work with the new object type
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     lock: {
       kind: 'CanNotDelete'
       name: 'myCustomLockName'
     }
     ```

   </details>

   <details>
   <summary>Tags</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#tags)
   - [ ] Update the current `tags` parameter as per the specs

   </details>

   <details>
   <summary>Managed Identities</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#managed-identities)
   - [ ] Add the `managedIdentitiesType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Remove any of the current identity parameters & variables
   - [ ] Add the the new `managedIdentities` parameter as per the specs to the template
   - [ ] Updated the deployment block as per the specs to enable it to work with the new object type
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     managedIdentities: {
       systemAssigned: true
       userAssignedResourcesIds: [
         nestedDependencies.outputs.managedIdentityResourceId
       ]
     }
     ```
   > **NOTE:** ⚠️ Make sure that if the module does not support e.g. user-assigned-identities, that you update the logic accordingly

   </details>

   <details>
   <summary>Private Endpoints</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#private-endpoints)
   - [ ] Add the `privateEndpointType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Update the current `privateEndpoints` parameter as per the specs (- should now reference the User-defined-type)
   - [ ] Updated the deployment block as per the specs to enable it to work with the new object type.
      >  Note: For any resource that only supports one service/groupID (e.g. `'vault'` for KeyVault, but NOT `'blob'` for StorageAccount) we can provide a default value for that property (hence there are 2 variants in the spec).
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     privateEndpoints: [
       {
         privateDnsZoneResourceIds: [
           nestedDependencies.outputs.privateDNSZoneResourceId
         ]
         subnetResourceId: nestedDependencies.outputs.subnetResourceId
         tags: {
           'hidden-title': 'This is visible in the resource name'
           Environment: 'Non-Prod'
           Role: 'DeploymentValidation'
         }
       }
     ]
     ```
   </details>

   <details>
   <summary>Customer Managed Keys</summary>

   > Reference to [AVM specs](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#customer-managed-keys)

   - [ ] Add the `customerManagedKeyType` described in the above reference to a `// Definitions` block at the bottom of the template file
   - [ ] Remove any of the current customer-managed-key parameters & variables
   - [ ] Add the the new `customerManagedKey` parameter as per the specs to the template
   - [ ] Update the `existing` resource references as per the specs
   - [ ] Updated the deployment block as per the specs to enable it to work with the new object type
         - ⚠️ BEWARE module-specific differences
         - Note also that the new schema SHOULD support system-assigned-identities. As this cannot be done in a single deployment, you can find a reference how this would look like [here](https://github.com/eriqua/bicep-registry-modules/blob/main/avm/res/cognitive-services/account/tests/e2e/system-assigned-cmk-encryption/main.test.bicep)
   - [ ] Check if any of the tests must be updated. The new block may look like
     ```Bicep
     customerManagedKey: {
       keyName: nestedDependencies.outputs.keyVaultKeyName
       keyVaultResourceId: nestedDependencies.outputs.keyVaultResourceId
       userAssignedIdentityResourceId: nestedDependencies.outputs.managedIdentityResourceId
     }
     ```
   > **NOTE:** ⚠️ Make sure that if the module does not support e.g. metrics, that you update the logic accordingly

   </details>

1. Other

   - [ ] Set version in `version.json` back to `0.1`
   - [ ] (Optional) Introduce the new `nullable` [feature](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/operators#logical) for parameters where-ever it makes sense to you (and ensure to test it). This enables us to simplify logic like in the following example
     ```Bicep
     // Old
     param attributesExp int = -1
     resource secret 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = {
       (...)
       properties: {
         attributes: {
           exp: attributesExp != -1 ? attributesExp : null
         }
       }
     }

     // New
     param attributesExp int?
     resource secret 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = {
       (...)
       properties: {
         attributes: {
           exp: attributesExp
         }
       }
     }
     ```

1. ReadMe
   - [ ] Regenerate all module ReadMe's & compile all module Bicep templates from the ground up. Ideally, remove the ReadMEs and regenerate them completely. Take note of any extra content (e.g., 'considerations') that were added manually and add them to the module's description metadata in the respective `main.bicep` file

</details>

# Helper script (work in progress)

<details>
<summary>Snippet</summary>

```PowerShell
#region helper functions

function Convert-Folders {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $FolderPath
    )

    # .bicep
    (Get-ChildItem -Path $FolderPath -Directory -Recurse -Filter '.bicep').FullName | Where-Object { $_ } | ForEach-Object {
        if (-not (Test-Path (Join-Path (Split-Path $_) 'modules'))) {
            $null = Rename-Item -Path $_ -NewName 'modules' -Force
        }
    }

    # .test
    # Add [e2e] folder
    (Get-ChildItem -Path $FolderPath -Directory -Recurse -Filter '.test').FullName | ForEach-Object {
        $newPath = Join-Path $_ 'e2e'
        if (-not (Test-Path $newPath)) {
            $null = New-Item -ItemType 'Directory' -Path $newPath
        }
    }

    # Move tests to new sub folder
    $testTopFolders = (Get-ChildItem -Path $FolderPath -Directory -Recurse -Filter '.test').FullName

    foreach ($testfolderPath in $testTopFolders) {

        $testCaseFolderPaths = (Get-ChildItem $testfolderPath -Directory -Exclude 'e2e').FullName

        foreach ($testFolderPath in $testCaseFolderPaths) {

            $expectedFolderName = Split-Path $testfolderPath -Leaf

            $newTestFolderPath = Join-Path (Split-Path $testFolderPath -Parent) 'e2e' $expectedFolderName
            if (-not (Test-Path $newTestFolderPath)) {
                $null = New-Item -ItemType 'Directory' -Path $newTestFolderPath
            }

            $originalTestFilePaths = Get-ChildItem $testfolderPath -File -Recurse

            foreach ($originalTestFilePath in $originalTestFilePaths) {
                $null = Move-Item -Path $originalTestFilePath -Destination $newTestFolderPath -Force
            }

            # If default folder [min/common], rename to new names [defaults/max]
            switch ($expectedFolderName) {
                'min' {
                    if (-not (Test-Path (Join-Path (Split-Path $newTestFolderPath) 'defaults'))) {
                        $null = Rename-Item -Path $newTestFolderPath -NewName 'defaults' -Force
                    }
                }
                'common' {
                    if (-not (Test-Path (Join-Path (Split-Path $newTestFolderPath) 'max'))) {
                        $null = Rename-Item -Path $newTestFolderPath -NewName 'max' -Force
                    }
                }
                Default {}
            }

            # Delete original folder
            $null = Remove-Item -Path $testFolderPath -Force
        }
    }

    # Rename test folder
    (Get-ChildItem -Path $FolderPath -Directory -Recurse -Filter '.test').FullName | Rename-Item -NewName 'tests'

    # Generate WAF folder
    $wafFolderPath = Join-Path $FolderPath 'tests' 'e2e' 'waf-aligned'
    if (-not (Test-Path $wafFolderPath)) {
        # Duplicate 'max' test folder
        $null = New-Item -Path $wafFolderPath -ItemType 'Directory' -Force
        $maxTestPath = Join-Path $FolderPath 'tests' 'e2e' 'max'
        $null = Copy-Item -Path "$maxTestPath/*" -Destination $wafFolderPath -Recurse
    }
}

function Set-ReadMe {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $FolderPath
    )

    $readMePaths = (Get-ChildItem -Path $FolderPath -File -Recurse -Filter 'readme.md').FullName

    # Remove original ReadMes
    $readMePaths | ForEach-Object { $null = Remove-Item -Path $_ -Force }

    # Regenerate new ReadMes
    # Set-AVMModule -ModuleFolderPath $FolderPath -Recurse
}

function Set-VersionFile {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $FolderPath
    )

    $versionPaths = (Get-ChildItem -Path $FolderPath -File -Recurse -Filter 'version.json').FullName

    foreach ($path in $versionPaths) {
        $originalContent = Get-Content -Path $path -Raw | ConvertFrom-Json
        $originalContent.version = '0.1'
        $originalContent | ConvertTo-Json -Depth 100 | Set-Content -Path $path -Force
    }
}

function Set-TestFiles {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $FolderPath
    )

    $testFilePaths = (Get-ChildItem -Path $FolderPath -File -Recurse -Filter 'main.test.bicep').FullName
    $testFolderPaths = $testFilePaths | ForEach-Object { Split-Path $_ }

    # [1] Update service shorts
    foreach ($testFolderPath in $testFolderPaths) {

        $testFolderName = Split-Path $testFolderPath -Leaf

        # If default folder [min/common], rename to new names [defaults/max]
        switch ($testFolderName) {
            'defaults' {
                $testContent = Get-Content (Join-Path $testFolderPath 'main.test.bicep') -Raw
                # Should remain `min` for now to work with PSRule config
                # $testContent = $testContent -replace "(param serviceShort string = '[a-zA-Z]+)min'", ("`$1{0}'" -f 'min')
                $null = Set-Content (Join-Path $testFolderPath 'main.test.bicep') -Value $testContent -Force
            }
            'max' {
                $testContent = Get-Content (Join-Path $testFolderPath 'main.test.bicep') -Raw
                $testContent = $testContent -replace "(param serviceShort string = '[a-zA-Z]+)com'", ("`$1{0}'" -f 'max')
                $null = Set-Content (Join-Path $testFolderPath 'main.test.bicep') -Value $testContent -Force
            }
            'waf-aligned' {
                $testContent = Get-Content (Join-Path $testFolderPath 'main.test.bicep') -Raw
                $testContent = $testContent -replace "(param serviceShort string = '[a-zA-Z]+)com'", ("`$1{0}'" -f 'waf')
                $null = Set-Content (Join-Path $testFolderPath 'main.test.bicep') -Value $testContent -Force
            }
            Default {}
        }
    }

    foreach ($testFilePath in $testFilePaths) {
        $testContent = Get-Content $testFilePath -Raw

        # [2] Remove telemetry
        $testContent = $testContent -replace "@description\('.+\(GUID\)\.'\)(\r\n|\r|\n){1}param enableDefaultTelemetry.+(\r\n|\r|\n){2}", ''
        $testContent = $testContent -replace '.*enableDefaultTelemetry: enableDefaultTelemetry.*(\r\n|\r|\n){1}', ''

        # [3] Update RG name
        $testContent = $testContent -replace "(param resourceGroupName string = ')ms.(.+)", '$1dep-${namePrefix}-$2'

        # [4] Idempotency & main.bicep reference
        $testContent = $testContent -replace "module testDeployment '\.\.\/\.\.\/main\.bicep' = {", "@batchSize(1)`r`nmodule testDeployment '../../../main.bicep' = [for iteration in [ 'init', 'idem' ]: {"
        $testContent = $testContent -replace "name: '\`${uniqueString\(deployment\(\)\.name, location\)}-test-\`${serviceShort}'", "name: '`${uniqueString(deployment().name, location)}-test-`${serviceShort}-`${iteration}'"

        # [5] diagnosticsTemplateReference
        $testContent = $testContent -replace '.+diagnostic.dependencies.bicep', "module diagnosticDependencies '../../../../../../utilities/e2e-template-assets/templates/diagnostic.dependencies.bicep"

        # [6] Replace namePrefix token with new format
        $testContent = $testContent -replace '\[\[namePrefix\]\]', '#_namePrefix_#'

        $null = Set-Content -Path $testFilePath -Value $testContent -Force
    }
}
#endregion

function Convert-CarmlToAvm {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $FolderPath,

        [Parameter(Mandatory = $false)]
        [string] $RepoRoot = 'C:\dev\ip\Azure-ResourceModules\ResourceModules'
    )

    # Load external functions
    # . (Join-Path $RepoRoot 'utilities' 'tools' 'Set-AVMModule.ps1')

    # [1] Convert folders
    Convert-Folders -FolderPath $FolderPath

    # [2] Set version.json back to 0.1
    Set-VersionFile -FolderPath $FolderPath

    # [3] Test file changes
    Set-TestFiles -FolderPath $FolderPath

    # [4] Regenerate ReadMe
    Set-ReadMe -FolderPath $FolderPath

}
Convert-CarmlToAvm -FolderPath 'C:\dev\ip\Azure-ResourceModules\ResourceModules\modules\key-vault\vault'
```

</details>

# Final steps: Migration
For the final AVM contribution a few more changes will be necessary as described in the following
- [ ] Update the reference to the diagnostic dependencies file in each test file that uses it to `avm/utilities/e2e-template-assets/templates/diagnostic.dependencies.bicep`
- [ ] Update the telemetry implementation as per it's new schema ([ref](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/#telemetry-enablement)). If the module references any external module, make sure to pass the `enableTelemetry` flag through like `enableTelemetry: enableTelemetry` to enable users to enable/disable for the entire deployment. Child resources should remain with the telemetry switched off for now.
- [ ] Remove telemetry from test cases
- [ ] Remove `version.json` files from child modules (as can't publish them yet)
- [x] #4409
  > This module has already been migrated to [AVM](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res). Only the AVM version is expected to receive updates / new features. Please do not work on improving this module in [CARML](https://aka.ms/carml).
- [ ] If the migrated module will be orphaned, add a `ORPHANED.md` file with the following content to the module in **AVM only**
  > This module is currently orphaned. Only security and bug fixes are being handled by the AVM core team at present. If interested in becoming a module owner (must be Microsoft FTE) for this orphaned module please comment on the issue here <LINK TO AVM REPO ISSUE>

These changes should be done after creating a fork of the [public bicep registory respository](https://github.com/Azure/bicep-registry-modules) and the module is added in the `/avm/res/` folder. From there you can not only test the module using the AVM CI, but also open the Pull Request to the Upstream repository.

**Comment by ChrisSidebotham** [comment]
@AlexanderSehr - Defaults will need to be `serviceShort` = `min` for PSRule to validate the non use of tags & Zones

**Comment by fabmas** [comment]
https://github.com/Azure/Azure-Verified-Modules/issues/451
